### PR TITLE
Users can login, integrate with the forum pages

### PR DESCRIPTION
**Pull request by Alex7Li**
See demo:
Peek 2022-04-29 05-02

### CODE REVIEW

**Review by mdunaevs — CHANGES_REQUESTED** [review]
Nice work. Video was great! Just fix up the merge conflicts and should be good to go

**Comment by bluo999** [comment]
Sorry, pushed some commits on accident.

**Review by mdunaevs — APPROVED** [review]
Approving

**Comment by Alex7Li** [comment]
> Sorry, pushed some commits on accident, reverted back to [f07dd3c](https://github.com/Claymore-Organization/Claymore/commit/f07dd3c075c718434cd46380f7bd21ce821fbbdc).

No worries, I didn't even notice, git is hard to use

**Pull request merged**
